### ISSUE TITLE
Setup.py broken

### ISSUE THREAD

**Issue by cesarvandevelde** [jxltom/gs_usb#1]
First of all, thank you for this useful module!

I had some issues installing the module in a virtual environment using pip.
I believe this is due to the directory structure. 
The source files are not inside a separate directory inside the repository, so `find_packages()` does not find anything and installs an empty package as a result.

# Steps to reproduce:

```bash
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install gs_usb

$ python -c "import gs_usb"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'gs_usb'

$ find venv -name "gs_usb*"
venv/lib/python3.8/site-packages/gs_usb-0.2.1.dist-info
```

The same issue occurs when the package is installed directly from git:
```
$ pip install git+https://github.com/jxltom/gs_usb.git
$ find venv -name "gs_usb*"
venv/lib/python3.8/site-packages/gs_usb-0.2.1.dist-info
```

# Proposed solution

* Move `__init__.py`, `__version__.py`, `constants.py`, `gs_usb.py`, `gs_usb_frame.py` to directory `gs_usb` inside the repository.
* Update setup.py:
  ```python
  with open(os.path.join(here, "gs_usb", "__version__.py")) as f:
  ```
* (Optional) Update `__init__.py` so that the main classes can be imported directly:

  ```python
  from .__version__ import __version__
  from .gs_usb import GsUsb
  from .gs_usb_frame import GsUsbFrame
  ```

**Comment by jxltom** [comment]
Hey @cesarvandevelde thanks for the report. I can reproduce it. And thanks for your suggestions, I've updated the code accordingly and released a new version in pypi.

Free feel to give it a try with ```pip install gs_usb>=0.2.2``` :heart:

**Comment by cesarvandevelde** [comment]
Great! Just tried and v0.2.2 works exactly as expected. Thanks for the quick update!
