### ISSUE TITLE
'GS_USB_MODE_NO_ECHO_BACK' flags seems not work

### ISSUE THREAD

**Issue by honorx** [jxltom/gs_usb#7]
Sorry for my poor english. Thank for you great work, this module is useful !

I had some issues using this module with candlelight_fw clone:
I use your test code to send & recv can frame, dev.read() always read back frame send by dev.send(). After read module's code, I add 'GS_USB_MODE_NO_ECHO_BACK' flags like this:

~~~
dev.start(mode=GS_USB_MODE_NORMAL | GS_USB_MODE_NO_ECHO_BACK)
~~~

but it's seems not work, dev.read() read back frame send by dev.send() again, so i check flags like this, it's seems ok:

~~~
iframe = GsUsbFrame()
if dev.read(iframe, 50) and iframe.echo_id != GS_USB_ECHO_ID:
    print("RX  {}".format(iframe))
~~~

I‘m not familiar with python and don't know how, any suggestions？

**Comment by jxltom** [comment]
The candlelight will receive duplicated messages if the messages are not received by any other CAN nodes. So make sure your candlelight is connected to other valid can device with same bitrate.

If still not working, please try to filter out the duplicated messages just like the code you mentioned

**Comment by honorx** [comment]
Sorry for my late reply, I get back to work right now.

The candlelight is connected to a valid CAN device but still got echo message with 'GS_USB_MODE_NO_ECHO_BACK' flag. If candlelight not connected to a valid CAN device, the 'echo_id' is '-1'.  I filter message by 'echo_id != GS_USB_ECHO_ID' now.

Thank you again !

**Comment by jxltom** [comment]
Thanks for the tips!
