### ISSUE TITLE
Bitrate 1000000 phase_seg1 is wrong

### ISSUE THREAD

**Issue by joonasbiolin** [jxltom/gs_usb#8]
https://github.com/jxltom/gs_usb/blob/master/gs_usb/gs_usb.py#L94 sets

        elif bitrate == 1000000:
            self.set_timing(prop_seg, 11, 2, sjw, 3)

I think that should be

        elif bitrate == 1000000:
            self.set_timing(prop_seg, 12, 2, sjw, 3)

as it is in https://github.com/HubertD/cangaroo/blob/b4a9d6d8db7fe649444d835a76dbae5f7d82c12f/src/driver/CandleApiDriver/CandleApiInterface.cpp#L64

**Comment by jxltom** [comment]
Hey thanks for finding it out! A typo, fixed in master branch!

**Comment by chemicstry** [comment]
Could you publish a new version with the fix?

**Comment by jxltom** [comment]
Sure, released v0.2.9!
